name: ci-flutter-test
on: [push]
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    
    - name: Get dependencies
        run: flutter pub get

    - name: Start release build
        run: flutter build appbundle